import { Contract, providers } from "ethers";
import { formatEther } from "ethers/lib/utils";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import Web3Modal from "web3modal";
import {
  CRYPTODEVS_DAO_ABI,
  CRYPTODEVS_DAO_CONTRACT_ADDRESS,
  CRYPTODEVS_NFT_ABI,
  CRYPTODEVS_NFT_CONTRACT_ADDRESS,
} from "../constants";
import styles from "../styles/Home.module.css";

export default function Home() {
  // eth balance of dao contract
  const [treasuryBalance, setTreasuryBalance] = useState("0");

  // number of proposals in the dao
  const [numProposals, setNumProposals] = useState("0");

  // array of all proposals created in the dao
  const [proposals, setProposals] = useState([]);

  // user's balance of CryptoDev NFTs
  const [nftBalance, setNftBalance] = useState(0);

  // fake nft token ID to purchase. Used when creating a proposal
  const [fakeNftTokenid, setFakeNftTokenid] = useState("");

  // one of 'Create Proposal' or 'View Proposals'
  const [selectedTab, setSelectedTab] = useState("");

  // true if waiting for a transaction to be mined
  const [loading, setLoading] = useState(false);

  // true if user has connected their wallet
  const [walletConnected, setWalletConnected] = useState(false);

  const web3ModalRed = useRef();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
